---
- name: Install Docker.io
  apt:
    name: docker.io
    state: present

- name: Docker Installation Verificaiom
  shell: docker --version
  register: docker_version

- name: Debug Docker Installation result
  debug:
    msg: "Yes, Docker is installed: {{ docker_version.stdout }}"

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes 

- name: Ship Nginx Service File
  template:
    src: nginx-service.j2
    dest: /etc/systemd/system/{{ nginx_service }}.service
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx_service 

- name: Enable Nginx Service
  systemd:
    name: "{{ nginx_service }}"
    enabled: yes
  notify: restart nginx_service

- name: Shell Nginx Systemd status
  shell: systemctl status nginx.service | grep Active | awk '{print $2}'
  register: systemctl_status

- name: Debug Nginx Systemd status
  debug:
    msg: "The nginx.status is {{ systemctl_status.stdout }}"

- name: Ship Nginx Config File
  template:
    src: conf.j2
    dest: /var/lib/nginx/conf.d/default.conf 
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx_service 

- name: Shell Server code from NGINX 
  shell: curl -o /dev/null -s -w "%{http_code}\n" http://localhost
  register: server_code

- name: Debug Server Code from NGINX
  debug:
    msg: "{{ server_code.stdout }}"
