---
- name: Project 2 Secure the Servers
  hosts: all
  become: yes
  vars_files:
    - secrets.yml   
  tasks:
    - name: Ping the machines
      ping:
    
    - name: (1) Ensure SSH key-based authentiction is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
      notify: Restart SSH

    - name: (1) Ensure no password login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH

    - name: (2) Allow all access to tcp on Debian
      ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
      loop:
        - 22
        - 80
        - 443
      when: ansible_facts['os_family'] == 'Debian'

    - name: (2) Install python3-firewall (required for firewalld module)
      package:
        name: python3-firewall
        state: present

    - name: (2) Install Firewalld on RedHat
      package:
        name: firewalld
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: (2) Allow all access to tcp on RedHat
      firewalld:
        service: https
        state: enabled
        permanent: true
        immediate: true
        offline: true
      when: ansible_facts['os_family'] == 'RedHat'

    - name: (3) Udpate packages on Ubuntu
      apt:
        name: "*"
        state: latest 
      when: ansible_facts['os_family'] == 'Debian'
    
    - name: (3) Udpate packages on RedHat
      dnf:
        name: "*"
        state: latest 
      when: ansible_facts['os_family'] == 'RedHat'

    - name: (6) Install Netstat on Debian
      apt:
        name: net-tools
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: (6) Install Netstat on RHEL
      yum:
        name: net-tools
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: (6) Open Port Scanning
      command: netstat -tulpn | column -t
      register: netstat_output

    - name: (6) Debug Open Ports
      debug:
        msg: "{{ netstat_output.stdout }}"
  
  handlers:
    - name: Restart SSH
      systemd:
        name: ssh
        state: restarted
