---
- name: Test Docker functionality
  hosts: WebServer01
  become: yes  # This enables privilege escalation
  vars_files:
    - vault.yml
  tasks:
    - name: Check if File Exists
      simple_file_check:
        path: "/tmp/test_file.txt"
        create: yes
      # roles:
      # - roles/7_Docker

