---
- name: Install Docker.io package
  apt:
    name: docker.io
    state: present
 
- name: Ensure Docker Service is enabled
  service:
    name: docker
    enabled: yes
    state: started

- name: Install Python and Pip
  become: yes
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Python Docker SDK
  become: yes
  pip:
    name: docker
    state: present

- name: Create Folder 
  file: 
    path: /var/jenkins_home
    owner: root
    mode: 1775
 
- name: Pull the latest official Jenkins image
  docker_image:
    name: "{{ jenkins_image }}"
    tag: "latest"
    source: pull

- name: Copy Jenkins Systemd Service File
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service
    mode: 0644

- name: Reload system daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Jenkins Service
  systemd:
    name: jenkins
    state: started
    enabled: yes 
