---
- name: Start Docker Service
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy Docker image tarball to the remote server
  copy:
    src: flask_image.tar
    dest: /tmp/flask_image.tar


- name: Load the Docker image on the remote server
  command: docker load -i /tmp/flask_image.tar

- name: Run the Flask app container
  docker_container:
    name: flask_app
    image: flask_image
    state: started
    ports:
      - "5001:5001"  # Map port 5001 inside the container to 5001 on the host
    restart_policy: always
