---
- name: Disable Swapoff
  command: swapoff -a

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: Add Kubernetes APT key
  shell: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes repo
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold kubelet kubeadm kubectl at current version
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: hold
