---
- name: Ensure Jenkins Namespace Exists
  community.kubernetes.k8s:
    name: jenkins-helm-medium
    api_version: v1
    kind: Namespace
    state: present
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config


- name: Add Jenkins Helm chart repo
  kubernetes.core.helm_repository:
    name: jenkins-project
    repo_url: "https://charts.jenkins.io"

- name: Update Helm Repo
  command: helm repo update
