---
- name: Add Jenkins Helm repo
  kubernetes.core.helm_repository:
    name: jenkins
    repo_url: https://charts.jenkins.io

- name: Update Helm repos
  command: helm repo update
  args:
    warn: false

- name: Install Jenkins Helm chart
  kubernetes.core.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    namespace: jenkins
    create_namespace: true
    values:
      controller:
        adminPassword: "yourAdminPasswordHere"
    state: present
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

