---
# tasks file for webserver
#- name: Update package cache
#  apt:
#    update_cache: yes

- name: Install NGINX webserver
  apt:
    name: nginx
    state: present

- name: Enable NGINX Webserver
  service:
    name: nginx
    state: started
    enabled: yes

    #- name: Get current http stats
    # community.general.nginx_status_info:
    # url: http://192.168.56.12/
    #register: result

- name: Debug NGINX status result
  debug:
    var: result

- name: Get Hostname Info
  command: hostname
  register: hostname_info
  
- name: Copy the shell script
  copy:
    src: get_system_info.sh
    dest: /tmp/get_system_info.sh
    mode: '0755'

- name: Execute The Shell Script
  command: /bin/bash /tmp/get_system_info.sh
  register: script_output


- name: Parse script output into variables
  set_fact:
    hostname: "{{ script_output.stdout_lines[0].split(': ')[1] }}"
    cpu_load: "{{ script_output.stdout_lines[1].split(': ')[1] }}"
    disk_usage: "{{ script_output.stdout_lines[2].split(': ')[1] }}"
    ram_usage: "{{ script_output.stdout_lines[3].split(': ')[1] }}"


- name: Deploy HTML J2 File 
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: Copy CSS File 
  copy:
    src: files/style.css
    dest: /var/www/html/style.css
    mode: '0644'


- name: Install Certbot
  apt:
    name: certbot
    state: present

- name: Install NGINX Certbot Plugin
  apt:
    name: python3-certbot-nginx
    state: present
 
- name: Creates Directory for SSL Certificate
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Generate Self-Signed SSL Certificate
  shell: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout /etc/nginx/ssl/nginx.key
    -out /etc/nginx/ssl/nginx.crt
    -subj "/C=US/ST=State/L=City/O=Organization/CN=192.168.56.12"
  args:
    creates: /etc/nginx/ssl/nginx.key

- name: Deploy NGINX Configuration with HTTPS
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

